# Generated by Django 4.0.3 on 2024-09-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-title',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
